[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = "3.1.3"
poem-openapi = { version = "5.1.2", features = ["swagger-ui"] }
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread"] }
